# coding: utf-8

"""
    JST Time API

    API that returns current time in JST (Japan Standard Time)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

from fastapi import FastAPI

from openapi_server.apis.time_api import router as TimeApiRouter

app = FastAPI(
    title="JST Time API",
    description="API that returns current time in JST (Japan Standard Time)",
    version="1.0.0",
)

app.include_router(TimeApiRouter)
